; parametri per invio mail
to=example1@mail.com
cc=example2@mail.com,example3@mail.com
subject=Test invio mail
bodyHTML=Questa è una mail di test
attachments=/percorso/al/file/file1.jpeg,/percorso/al/file/file2.png
