; Servizio mail di test
[test]
host=
auth=true
secure=
port=
user=[mail]
password=[password]
mail_from=no-reply@mail.it
name_from=Comune di @@

; Servizio mail di produzione
[prod]
host=
auth=true
secure=
port=
user=[mail]
password=[password]
mail_from=no-reply@mail.it
name_from=Comune di @@
