; ambiente id test
[pg_test]
host=
port=
dbname=
user=
password=
; tabella in cui cercare mail da inviare
table_queue=

; ambiente id produzione
[pg_prod]
host=
port=
dbname=
user=
password=
; tabella in cui cercare mail da inviare
table_queue=
